export const LOAD_ORDERS = "LOAD_ORDERS";
export const SET_VALUE_ORDERS_FILTERS = "SET_VALUE_ORDERS_FILTERS";
export const CLEAR_VALUE_ORDERS_FILTERS = "CLEAR_VALUE_ORDERS_FILTERS";
export const CLEAR_ALL_VALUE_ORDERS_FILTERS = "CLEAR_ALL_VALUE_ORDERS_FILTERS";
export const TOGGLE_FILTERS = "TOGGLE_FILTERS";
